In [27]:
# Salary_Data.csv
# location: https://mitu.co.in/dataset

In [28]:
import pandas as pd

#### import the dataset

In [30]:
df = pd.read_csv('Salary_Data.csv')
x = df['YearsExperience'].values
x = x.reshape(30,1)
y = df['Salary']

In [31]:
x.shape

(30, 1)

#### Holdout method

In [32]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, random_state=0,
                                                   test_size= 0.25)

#### Build linear regression model

In [33]:
from sklearn.linear_model import LinearRegression
reg = LinearRegression()
reg.fit(x_train,y_train)
print('Training acc: ', reg.score(x_train, y_train))
print('Testing acc: ', reg.score(x_test, y_test))

Training acc:  0.9395413526983522
Testing acc:  0.9779208335417602


#### K-Fold Method

In [34]:
from sklearn.model_selection import KFold

In [35]:
kf = KFold(n_splits= 5, random_state= 0, shuffle= True)

In [36]:
for train, test in kf.split(x, y):
    print(train,'\n', test)

[ 0  1  3  4  5  6  7  8  9 11 12 14 15 16 17 18 19 20 21 22 23 25 27 29] 
 [ 2 10 13 24 26 28]
[ 0  1  2  3  4  6  7  8  9 10 12 13 14 15 18 19 20 21 23 24 25 26 28 29] 
 [ 5 11 16 17 22 27]
[ 0  2  3  4  5  6  7  9 10 11 12 13 15 16 17 18 19 21 22 24 25 26 27 28] 
 [ 1  8 14 20 23 29]
[ 0  1  2  3  5  8 10 11 12 13 14 15 16 17 20 21 22 23 24 25 26 27 28 29] 
 [ 4  6  7  9 18 19]
[ 1  2  4  5  6  7  8  9 10 11 13 14 16 17 18 19 20 22 23 24 26 27 28 29] 
 [ 0  3 12 15 21 25]


#### Extract  train and test data

In [37]:
for train, test in kf.split(x, y):
    print('Train:', x[train].flatten())
    print('Test:', x[test].flatten())

Train: [ 1.1  1.3  2.   2.2  2.9  3.   3.2  3.2  3.7  4.   4.   4.5  4.9  5.1
  5.3  5.9  6.   6.8  7.1  7.9  8.2  9.   9.6 10.5]
Test: [ 1.5  3.9  4.1  8.7  9.5 10.3]
Train: [ 1.1  1.3  1.5  2.   2.2  3.   3.2  3.2  3.7  3.9  4.   4.1  4.5  4.9
  5.9  6.   6.8  7.1  8.2  8.7  9.   9.5 10.3 10.5]
Test: [2.9 4.  5.1 5.3 7.9 9.6]
Train: [ 1.1  1.5  2.   2.2  2.9  3.   3.2  3.7  3.9  4.   4.   4.1  4.9  5.1
  5.3  5.9  6.   7.1  7.9  8.7  9.   9.5  9.6 10.3]
Test: [ 1.3  3.2  4.5  6.8  8.2 10.5]
Train: [ 1.1  1.3  1.5  2.   2.9  3.2  3.9  4.   4.   4.1  4.5  4.9  5.1  5.3
  6.8  7.1  7.9  8.2  8.7  9.   9.5  9.6 10.3 10.5]
Test: [2.2 3.  3.2 3.7 5.9 6. ]
Train: [ 1.3  1.5  2.2  2.9  3.   3.2  3.2  3.7  3.9  4.   4.1  4.5  5.1  5.3
  5.9  6.   6.8  7.9  8.2  8.7  9.5  9.6 10.3 10.5]
Test: [1.1 2.  4.  4.9 7.1 9. ]


#### Apply KFold

In [41]:
train_acc = []
test_acc = []

for train, test in kf.split(x, y):
    reg.fit(x[train], y[train])
    print('Train Acc:', reg.score(x[train], y[train]))
    print('Test Acc:', reg.score(x[test], y[test]), '\n')
    train_acc.append(reg.score(x[train], y[train]))
    test_acc.append(reg.score(x[test], y[test]))

Train Acc: 0.9411949620562126
Test Acc: 0.988169515729126 

Train Acc: 0.9612542631539638
Test Acc: 0.9257917429817739 

Train Acc: 0.9635908373578711
Test Acc: 0.9252385867407542 

Train Acc: 0.9625173469912476
Test Acc: 0.8785189123539608 

Train Acc: 0.9540189535215173
Test Acc: 0.9646120517676184 



In [44]:
train_acc

[0.9411949620562126,
 0.9612542631539638,
 0.9635908373578711,
 0.9625173469912476,
 0.9540189535215173]

In [45]:
len(train_acc)

5

In [42]:
sum(train_acc)/len(train_acc)

0.9565152726161624

In [43]:
sum(test_acc)/len(test_acc)

0.9364661619146467

#### Apply the kfold to classification

In [49]:
df = pd.read_csv('banknotes.csv')

x = df.drop('Class', axis = 1)
y = df['Class']

In [50]:
df.head()

,Variance,Skewness,Curtosis,Entropy,Class
0,3.62160,8.6661,-2.8073,-0.44699,0
1,4.54590,8.1674,-2.4586,-1.46210,0
2,3.86600,-2.6383,1.9242,0.10645,0
3,3.45660,9.5228,-4.0112,-3.59440,0
4,0.32924,-4.4552,4.5718,-0.98880,0


In [51]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score
dt = DecisionTreeClassifier(random_state= 0)

In [55]:
for train, test in kf.split(x, y):
    dt.fit(x.iloc[train, :], y[train])
    y_pred = dt.predict(x.iloc[test, :])
    print('Acc:', accuracy_score(y[test], y_pred))

Acc: 0.9927272727272727
Acc: 0.9854545454545455
Acc: 0.9671532846715328
Acc: 0.9963503649635036
Acc: 0.9671532846715328


In [57]:
y.value_counts()

Class
0    762
1    610
Name: count, dtype: int64

In [61]:
print('0:', round(y.value_counts()[0]/len(y) * 100,2))
print('1:', round(y.value_counts()[1]/len(y) * 100,2))

0: 55.54
1: 44.46


#### Stratified K Fold

In [62]:
from sklearn.model_selection import StratifiedGroupKFold

In [64]:
skf = StratifiedGroupKFold(n_splits= 5, random_state= 0, shuffle = True)

In [71]:
for train, test in skf.split(x, y):
    print('0:', round(y[train].value_counts()[0]/ len(y[train]) * 100,2))
    print('1:', round(y[train].value_counts()[1]/ len(y[train]) * 100,2))
    print()

0: 55.51
1: 44.49

0: 55.54
1: 44.46

0: 55.54
1: 44.46

0: 55.54
1: 44.46

0: 55.54
1: 44.46



# Leave one out Cross Validation

In [76]:
import warnings
warnings.filterwarnings('ignore')

In [79]:
df = pd.read_csv('Salary_Data.csv')
x = df.iloc[:,0:1]
y = df.iloc[:,1]


reg = LinearRegression()
reg.fit(x, y)
print('Acc:', reg.score(x, y))

Acc: 0.9569566641435086


In [81]:
from sklearn.model_selection import LeaveOneOut

In [82]:
loo = LeaveOneOut()

In [83]:
acc = []
for train, test in loo.split(x, y):
    reg.fit(x.iloc[train, :], y[train])
    print('Training', reg.score(x.iloc[train, :], y[train]))
    acc.append(reg.score(x.iloc[train, :], y[train]))

Training 0.9545718627582311
Training 0.958587833405514
Training 0.9540131952134367
Training 0.9547596050416939
Training 0.9564834700633973
Training 0.9567656356216794
Training 0.9582130226100234
Training 0.9561104765296161
Training 0.960131056387674
Training 0.9568429100750674
Training 0.9566358411849186
Training 0.9590717906178837
Training 0.9583451123530368
Training 0.9589144294828913
Training 0.9589969710338275
Training 0.9576475411252547
Training 0.959773235578126
Training 0.9593278332138555
Training 0.9568995000453171
Training 0.9626193838388891
Training 0.9565827022105926
Training 0.9573493387246972
Training 0.9556449678469764
Training 0.9596859966454178
Training 0.9546529616010134
Training 0.9565495539413051
Training 0.9533412232144192
Training 0.954858051154339
Training 0.9520924674244241
Training 0.9527733741688964


In [84]:
sum(acc)/ len(acc)

0.9569413781037472