In [4]:
import numpy as np

In [5]:
# create an array
x = np.array([34,56,356,67,89,21])

In [6]:
x

array([ 34,  56, 356,  67,  89,  21])

In [7]:
print(x)

[ 34  56 356  67  89  21]


In [8]:
x[2]

356

In [9]:
y = np.array([43,56,'string',56.44,5])

In [10]:
y

array(['43', '56', 'string', '56.44', '5'], dtype='<U32')

In [11]:
x.dtype

dtype('int64')

In [12]:
x.shape

(6,)

In [13]:
x

array([ 34,  56, 356,  67,  89,  21])

In [14]:
x + 10

array([ 44,  66, 366,  77,  99,  31])

In [15]:
x * 2

array([ 68, 112, 712, 134, 178,  42])

In [16]:
new = x * 2 + 4.5
new

array([ 72.5, 116.5, 716.5, 138.5, 182.5,  46.5])

In [17]:
np.arange(12)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [18]:
np.arange(5,20)

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [19]:
np.arange(5,21,3.5)

array([ 5. ,  8.5, 12. , 15.5, 19. ])

In [20]:
np.arange(14,2,-2)

array([14, 12, 10,  8,  6,  4])

In [21]:
np.arange(-10,10,0.5)

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,  -5. ,  -4.5,  -4. ,  -3.5,  -3. ,  -2.5,  -2. ,  -1.5,
        -1. ,  -0.5,   0. ,   0.5,   1. ,   1.5,   2. ,   2.5,   3. ,
         3.5,   4. ,   4.5,   5. ,   5.5,   6. ,   6.5,   7. ,   7.5,
         8. ,   8.5,   9. ,   9.5])

In [22]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [24]:
# two dimensional arrays
t = np.array([[34,23,56],[78,34,29],[56,78,72],[54,14,89]])

In [25]:
t

array([[34, 23, 56],
       [78, 34, 29],
       [56, 78, 72],
       [54, 14, 89]])

In [26]:
t.shape

(4, 3)

In [27]:
t.ndim

2

In [28]:
t.flatten()

array([34, 23, 56, 78, 34, 29, 56, 78, 72, 54, 14, 89])

In [30]:
t.reshape(3,4)

array([[34, 23, 56, 78],
       [34, 29, 56, 78],
       [72, 54, 14, 89]])

In [33]:
t.reshape(-1,2)

array([[34, 23],
       [56, 78],
       [34, 29],
       [56, 78],
       [72, 54],
       [14, 89]])

In [34]:
t.reshape(6,-1)

array([[34, 23],
       [56, 78],
       [34, 29],
       [56, 78],
       [72, 54],
       [14, 89]])

In [37]:
t.reshape(3,2,2)

array([[[34, 23],
        [56, 78]],

       [[34, 29],
        [56, 78]],

       [[72, 54],
        [14, 89]]])

In [38]:
x

array([ 34,  56, 356,  67,  89,  21])

In [39]:
x[3:]

array([67, 89, 21])

In [40]:
x[:4]

array([ 34,  56, 356,  67])

In [42]:
t

array([[34, 23, 56],
       [78, 34, 29],
       [56, 78, 72],
       [54, 14, 89]])

In [43]:
t[0:3,0:2]

array([[34, 23],
       [78, 34],
       [56, 78]])

In [44]:
t[0:3,2]

array([56, 29, 72])

In [45]:
z = [45,67,45,45,68,34,31]

In [46]:
np.unique(z)

array([31, 34, 45, 67, 68])

In [47]:
x

array([ 34,  56, 356,  67,  89,  21])

In [48]:
x.mean()

103.83333333333333

In [49]:
x.max()

356

In [53]:
t

array([[34, 23, 56],
       [78, 34, 29],
       [56, 78, 72],
       [54, 14, 89]])

In [55]:
t.transpose()

array([[34, 78, 56, 54],
       [23, 34, 78, 14],
       [56, 29, 72, 89]])

In [60]:
arr1 = np.array([1,2,3])
arr2 = np.array([2,2,3])

In [61]:
# comparing array
arr_equal = np.array_equal(arr1, arr2)
arr_equal

False

In [62]:
# element wise comparison
compare = arr1 == arr2
compare

array([False,  True,  True])

In [63]:
t

array([[34, 23, 56],
       [78, 34, 29],
       [56, 78, 72],
       [54, 14, 89]])

In [64]:
# statical function

std_dev = np.std(t)
std_dev

23.478565875188277

In [65]:
np.var(t)

551.2430555555555

In [66]:
x

array([ 21,  34,  56,  67,  89, 356])

In [68]:
# searching

np.where(x == 89)

(array([4]),)

In [69]:
np.where(t == 23)

(array([0]), array([1]))

In [76]:
# generate random numbers
random_int = np.random.randint(1,10)
random_int

5